# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'ROCKET SCIENCE'
tagline:          'QA Automation, Continuous Integration & Delivery'
description:      'DEPLOYMENT TIME</br>WITH FAILS & FUCKUPS'
url:              http://alexander.ilyin.eu
baseurl:          /

author:
  name:           'Alexander Ilyin'
  url:            https://twitter.com/alexander_ilyin

paginate:         5