# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'TEST INTEGRATE DEPLOY REPEAT'
tagline:          'QA Automation, Continuous Integration & Delivery'
description:      'Best Practices for developing Android, iOS, Windows Phone and Web applications by <a href="https://twitter.com/alexander_ilyin" target="_blank">@alexander_ilyin</a>'
url:              http://alexander.ilyin.eu
baseurl:          /

author:
  name:           'Alexander Ilyin'
  url:            https://twitter.com/alexander_ilyin

paginate:         5